METRICS = [
    "Caption",
    "Timestamp",
    "Thumbnail URL",
    "Accounts reached",
    "Comments",
    "Likes",
    "Saved",
    "Shares",
    "Initial Plays",
    "Reels interactions",
    # "Video View Total Time (milliseconds)",
    # "Reels Average Watch Time (milliseconds)",
    "Total Plays",
    "Replays",
    "Like PCT",
    "Comment PCT",
    "Share PCT",
    "Save PCT",
    "Hashtags",
    "Media URL",
]
